In [1]:
import tensorflow as tf

In [2]:
import keras

In [4]:
# 1a. create a 2D array in Tensorflow and find max per row
import tensorflow as tf
mat=tf.constant([[12,23,34,45],[2,25,1,8],[5,7,78,12],[95,21,47,20]])
print(mat)
matmax=tf.math.reduce_max(mat,axis=1)
print(matmax)

tf.Tensor(
[[12 23 34 45]
 [ 2 25  1  8]
 [ 5  7 78 12]
 [95 21 47 20]], shape=(4, 4), dtype=int32)
tf.Tensor([45 25 78 95], shape=(4,), dtype=int32)


In [5]:
# 1b. Perform vector additio
a=tf.constant([[1,2,3,4],
               [2,4,5,6],
               [1,1,1,1]])
b=tf.constant([[1,1,1,1],
               [7,2,2,3],
               [2,2,2,2]])
c=tf.add(a,b)
print(c)

tf.Tensor(
[[2 3 4 5]
 [9 6 7 9]
 [3 3 3 3]], shape=(3, 4), dtype=int32)


In [6]:
# 1c.Add a tensor and a list of same shape in tensorflow
list=[[1,2,3],[4,5,6],[1,1,1]]
a=tf.constant([[2,3,4],
               [1,3,4],
               [6,3,1]])
c=tf.add(list,a)
print(c)

tf.Tensor(
[[ 3  5  7]
 [ 5  8 10]
 [ 7  4  2]], shape=(3, 3), dtype=int32)
